version: '2.4'

services:
  kahiin-db:
    image: mysql:8.0
    container_name: kahiin-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-kahiin}
      MYSQL_USER: ${DB_USER:-kahiin}
      MYSQL_PASSWORD: ${DB_PASSWORD:-kahiin}
    volumes:
      - ./source/kahiin-db:/kahin-db
      - kahiin-db-data:/var/lib/mysql
    working_dir: /kahiin-db
    network_mode: host
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

  kahiin-server:
    image: python:3.12-slim-bullseye
    container_name: kahiin-server
    restart: unless-stopped
    depends_on:
      kahiin-db:
        condition: service_healthy
    volumes:
      - ./source/kahiin:/kahiin
    working_dir: /kahiin
    command: >
      bash -c "pip install -r requirements.txt &&
              python app.py"
    environment:
      DB_HOST: localhost
      DB_USER: ${DB_USER:-kahiin}
      DB_PASSWORD: ${DB_PASSWORD:-kahiin}
      DB_NAME: ${DB_NAME:-kahiin}
    network_mode: host

volumes:
  kahiin-db-data: